In [ ]:
import pandas as pd
import csv
from datetime import datetime

In [ ]:

def percentage(col1, col2) -> float:

    """
    Function to calaculate specific rate between 2 values

    Parameters
    ----------
    col1: float
    col2: float

    Returns
    -------
    float

    """
    return ((col1) / (col2) * 100)

def iso_date(date) -> datetime:

    """
    Function that convert str to datetime and specific format.

    Parameters
    ----------
    date: str

    Returns
    -------
    i: datetime (iso format)

    """

    date = datetime.strptime(date, '%Y.%m.%d')
    
    return date.isoformat()

def convert_to_int(column) -> int:

    """
    Function that convert a value to int

    Parameters
    ----------
    column: str/float

    Returns
    -------
    int

    """

    return column.astype('int')

In [ ]:

# read raw data
data = pd.read_csv("dataset.csv")

# change format date to iso format
for i, row in data.iterrows():

    data.loc[i, 'summary_date_iso'] = iso_date(row['summary_date'])

# group data by date and campaign
report = data.groupby(['summary_date_iso','campaign_name'], as_index=False)['impressions', 'clicks', 'installs', 'spend'].sum()

In [ ]:
# calculate CTR and CPI
report['CPI'] = percentage(report['spend'],report['installs'])
report['CTR'] =  percentage(report['clicks'],report['impressions'])

In [55]:
report[['impressions', 'clicks', 'installs']] = convert_to_int(report[['impressions', 'clicks', 'installs']])

report.to_csv('report.csv')

report

,summary_date_iso,campaign_name,impressions,clicks,installs,spend,CPI,CTR
0,2022-06-01T00:00:00,Super campaign 10,0,590558,17316,468.910000,2.707958,inf
1,2022-06-01T00:00:00,Super campaign 13,0,0,2,0.000000,0.000000,NaN
2,2022-06-01T00:00:00,Super campaign 16,3363808,4074,766,172.641300,22.538029,0.121113
3,2022-06-01T00:00:00,Super campaign 6,2004048,6768,18,9.265945,51.477472,0.337716
4,2022-06-02T00:00:00,Super campaign 10,0,28844,13206,947.310000,7.173330,inf
...,...,...,...,...,...,...,...,...
252,2022-07-30T00:00:00,Super campaign 9,0,0,2,0.000000,0.000000,NaN
253,2022-07-31T00:00:00,Super campaign 10,0,0,0,0.000000,NaN,NaN
254,2022-07-31T00:00:00,Super campaign 16,1086188,34170,78,164.589750,211.012500,3.145864
255,2022-07-31T00:00:00,Super campaign 6,1124080,21316,96,35.750000,37.239583,1.896306
256,2022-07-31T00:00:00,Super campaign 9,0,0,2,0.000000,0.000000,NaN